language: java
jdk: oraclejdk8
before_install:
- chmod +x gradlew
before_deploy:
- chmod ugo+x deploy.sh
script:
- bash ./gradlew clean build warNoStatic warCopy zipGetVersion zipStatic
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/garystafford/spring-music.git
  - secure: a9vmysUsyHe85ojVqc5+3Qq0o0z1lSwdAaUW2cFri9N4dhU73v/u4DJ9DFTJmzORpeH+QOpbnamJo+9GfHTkYNvcOqb72h2k8KUXLNdKM6zhpau5RcBcvNPYFRAap+O7/r2Rn+YrEtkk5IKF6MrE2msP5ot3f3uX7qtpOcQXkGQCLRQe39tG7zVYNy1RWTHMKJX0DLRpIVo0B//8x/vdI3PnNYSin/ijuC6kv94rcHrtomvM1DiRJvoSdgzRWjIPM6sMgu130rPxN1oxv2gJ+H78eOXSh1bj5Z2dVtC9G5863086zcQmmvWF8jluE6b9Ji7rFnyvpOLZjaAq9VK5iafqmE1g2m45XlgMTId92PIgH9BTd3C3w4JnlT6Y7sE5TzoyDIVLjWARAZlU8XFS/uNIXD4gFYdT0CcsPU8HZIqt4/eMCSMLk6mPfBeXWs3gqRSNZg8JZ7hdAVnYTq6ZZir1UZnQe+9JCmAxqmdSmEmG5ocFLpseyR1fgxPTvXisyWDwDm1TQ0rU3MhdI/A4oR3OiTGwzG9Yn8MK2Nn4QDvoWDYThXLRxRJGiN48FOwf4uWWM1FaNUwULdlAH6V602pi1OJ/Fi9D2TZIHxhWDcTXj5wfBWWpSRZM4Y4iq/A/6Un8gG38AcCAW3yqbqcrSGcOMCt1jAE/RMkpFbByi4g=
notifications:
  slack:
    secure: lQ9wlH21js1OMwStoDjMjPc/G1zdfE0UdbiR1kVunJ4FIowlLW6JHdU1186Jz8ouXoyzXhpT3NMj617QLm4alznBW0ndreieS9sybjhJS1gMNtLKJR9O2LXAwCWH+tQkXGDVOLygSvR/2Xlom+lFHr5Xg/IgWcGB3CO2pIIML3dOCojUstwKhoYSoxO8LpMFsZtXD+qpKeHTbVF7QSRXb3ghIYC15MNOs508z8Ed7vip5iNn/itUzSPsH1thBY2f80Fq4bh6WvQhvo2SsaUa01lw+btMbXA2FCQ3jAhZZG1SauuWXpEhgQ3IfOuWJRuDXY/kX+Q+dYjGqIH9qTT25svGEeMnUykfW3m1UrPe2G+9tJ9nyfWNxePlm4gWlzZhGha04UxVwBi+5DqiiS231ztDMQ/mWwp2Z6kUAgu97Om5lRov3zDXyI03vKCmiCTJx7NVLOiiWIqNqLth/ALfcdjtnHnwIH6bP+u26EmtHt5WjTP+PFbqIsFcLLtEQRlsFhUPhJY/2xO+jQrt0prYB0LC8hO9jDct9VIgju3D2y2BenecewV/GrHMVjhXxYbsW1gNAckZ34ZFUkfMRJegpCt81/vhhkrgJPmBespONROrcPI2ILSJTAXbUuwRIZ8Dcrnmg8/P/MbNsAIxrY4jH7RHV1JWM7/aoFaLsCUpj00=
